### ISSUE TITLE
Fehler 13 still operative even after 24 hours

### ISSUE THREAD

**Issue by mtrinkau** [corona-warn-app/cwa-app-ios#2758]
EDIT 210523: Corona-Warn-App Open Source Team:

Version 2.2.1 (0)
IPhone 11 Pro 
IOS 14.5.1.

1. Did this occur just after updating CWA from 2.1 to 2.2?
2. Did this issue occur when receiving a test result, and if so positive or negative?
3. Any other occurrence at the same time, i.e. another error notification, i.e. NoExposureWindow?
4. Does the error occur when you open the app, or on its own.
5. When was the last risk check?
6. Did you have the same error before using 2.2, and if yes in which context (updating CWA, QR code scan, getting test result)

Answers: 

1. After the update. Never had this issue before.
2. No. Just wanted to check my status.
3. No
4. Only when I open the app and try to update the status.
5. Day before yesterday at 01:15 am
6. No. I never had this issue before.

---
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)
error report ID ID: 2EC7ECO7FECO3E9B6E3A

**Comment by Ein-Tim** [comment]
Hey @mtrinkau 

Could you please let us know which version of the Corona-Warn-App you're using? 

Thank you!

**Comment by mtrinkau** [comment]
Hi - am using Version 2.2.1 (0)

Best

**Comment by Ein-Tim** [comment]
@mtrinkau 

Okay, thank you for the information.
Could you please also provide us with your iOS version and your iPhone Model? 

Thank you very much and have a nice Sunday!

**Comment by mtrinkau** [comment]
Thank you for the prompt response.
IPhone 11 Pro and IOS 14.5.1. 

Best & a nice Sunday too

**Comment by Ein-Tim** [comment]
Okay, thank you very much @mtrinkau!

We had some more users reporting this issue in version 1.15 as well as version 2.0, but this should have been fixed in version 2.1. 
One of the community managers (cc @dsarkar) will soon come back to you with further instructions or requests.

Thank you for reporting this issue and helping to improve the Corona-Warn-App!

**Comment by dsarkar** [comment]
@mtrinkau Thank you for reporting! 
@Ein-Tim Thanks!

@mtrinkau Could you provide us with an error report:

1. start the error report logging
2. Wait 24 h before sending the error report. If no error 13 notification has occurred, keep the logging active (i.e. don't send/stop/delete the report) until you get the error 13 notification.
3. then send the report and afterwards you can stop the error report logging.

This is a new feature in CWA version 2.2. For more information see the FAQ entry (there is also a link to a blog article)

https://www.coronawarn.app/en/faq/#error_log
https://www.coronawarn.app/de/faq/#error_log

In the meantime provide us also with more information, please:
1. Did this occur just after updating CWA from 2.1 to 2.2?
2. Did this issue occur when receiving a test result, and if so positive or negative?
3. Any other occurrence at the same time, i.e. another error notification, i.e. NoExposureWindow?
4. Does the error occur when you open the app, or on its own.
5. When was the last risk check?
6.  Did you have the same error before using 2.2, and if yes in which context (updating CWA, QR code scan, getting test result)


Many thanks for your feedback. Best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by mtrinkau** [comment]
Thanks very much. I appreciate your support ! 
I have started the error report. 
As to your questions:

1: After the update. Never had this issue before.
2: No. Just wanted to check my status.
3: No
4: Only when I open the app and try to update the status.
5: Day before yesterday at 01:15 am
6: No. I never had this issue before.

Thanks again !
Best 
Mtrinkau

**Comment by dsarkar** [comment]
@mtrinkau Thanks. We wait for your error report and the ID in let's say about a day or so (after it has occurred). 

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by mtrinkau** [comment]
Hi there - here comes the Error ID. 
The issue stills persists.

ID: 2EC7ECO7FECO3E9B6E3A

Best
mtrinkau

**Comment by dsarkar** [comment]
Hi @mtrinkau Thank you. Your information is forwarded to the internal ticket. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Hi @mtrinkau 

Could you update to version 2.5 and give us some feedback on whether this issue still persists? Thanks!

**Comment by heinezen** [comment]
Hello everyone,

Occurences of Error 13/Fehler 13 should be fixed with the recent CWA release 2.5. Please update your app and report back if the error still persists for you when using the newest version. We will close the issue for now.

----
Corona-Warn-App Open Source Team

**Comment by mtrinkau** [comment]
Hi there - unfortunately the issue still persists…

Best
Marc

**Comment by Ein-Tim** [comment]
Hi @mtrinkau 

Thank you for your feedback. Could you let us know if your still on iOS 14.5.1 and if you're on the version 2.5 of the app? 

Thank you!

**Comment by mtrinkau** [comment]
Hi there,

Am on IOS 14.6 now and App version 2.5.1.

Best
M

**Comment by Ein-Tim** [comment]
@mtrinkau Thank you for the update. Could you upload a screenshot of your "Begegnungsüberprüfungen" here?
Below you find an instruction on how you can find the screen I mean. To upload a photo on GitHub, you have to either use https://GitHub.com or the mobile app (https://github.com/mobile). You can't upload the screenshot via mail, sadly.

Please make a screenshot of: 

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` 

and share it with us here. Thank you!

**Comment by ndegendogo** [comment]
@mtrinkau please try to remember as much details related to your Error-13 message; especially:
1) Can you remember the date and time? (even roughly - so we can try to map the message to the timing if your exposure checks)
2) Do you remember more details: did you open the app / were you using it at that time? Or was the failing check triggered from background processing?
3) If you were using the app: do you remember what you did / which menus / tabs / activities?
4) I assume we are still talking about the same device of your original report - right?
5) Do you know since when you are on cwa 2.5? Did you upgrade manually, or got it with the automatic roll-out? Do you know if this was the first check after the update?
6) Do you usually close cwa just with the home button, or do you swipe it out of memory?
7) Do you get the error message repeatedly, or was it a one-time occurance?

**Comment by ndegendogo** [comment]
A few observations and thoughts:
* error 13 means that cwa has [called ENF too often](https://developer.apple.com/documentation/exposurenotification/enerror/code/ratelimited). Apple specifies a maximum of [6 calls per 24 hours](https://developer.apple.com/documentation/exposurenotification/enmanager/3586331-detectexposures)
* the behaviour of error 13 looks like a race condition
* the first part of risk calculation is well synchronized and bound to a single thread via a [DispatchQueue](https://github.com/corona-warn-app/cwa-app-ios/blob/8c14cecc01b682510a4f57b837f6d374d9411836/src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift#L166). However, I found no documentation on which thread iOS will schedule the completion handler; so we have to assume the worst case here - it could be the same thread as the caller, or the event thread, or any other thread; and the strategy for this could differ between iOS versions; and the thread itself could depend on runtime conditions like iPhone model / number of CPUs / current power saving mode / other apps running in parallel etc
* a risk calculation is requested from many places in the code, eg [from startup](https://github.com/corona-warn-app/cwa-app-ios/blob/8c14cecc01b682510a4f57b837f6d374d9411836/src/xcode/ENA/ENA/Source/AppDelegate%20%26%20Globals/AppDelegate.swift#L148), or from [returning to the home tab](https://github.com/corona-warn-app/cwa-app-ios/blob/8c14cecc01b682510a4f57b837f6d374d9411836/src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift#L124). Especially on launch of cwa, two such triggers occur in a very short time interval, and both make it into the queue
* the state machine of the risk calculation [is designed](https://github.com/corona-warn-app/cwa-app-ios/blob/8c14cecc01b682510a4f57b837f6d374d9411836/src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift#L100) to prevent a second calculation from starting while the previous is still running. However, in some error cases the state machine stops with error, but the task continues to run (eg timeout on fetching new keys from the server, but unprocessed keys are already available on the device, [see also this comment](https://github.com/corona-warn-app/cwa-app-ios/blob/8c14cecc01b682510a4f57b837f6d374d9411836/src/xcode/ENA/ENA/Source/Services/Risk/Provider/__tests__/RiskProviderTests.swift#L312))
* [this check](https://github.com/corona-warn-app/cwa-app-ios/blob/8c14cecc01b682510a4f57b837f6d374d9411836/src/xcode/ENA/ENA/Source/Services/Risk/Provider/RiskProvider.swift#L333) is designed to prevent a risk calculation if the previous is less than 4 hours ago. The 4 hours correspond ro Apple's rate limit of max 6 times per 24 hours. However, the used timestamp corresponds to a [successfully finished](https://github.com/corona-warn-app/cwa-app-ios/blob/8c14cecc01b682510a4f57b837f6d374d9411836/src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift#L109) risk calculation. It will not prevent a second call to ENF if the previous calculation failed or is still running.

My suggestion for a fix would be to **add a second timestamp** corresponding to the call of [ENManager.detectExposures](https://github.com/corona-warn-app/cwa-app-ios/blob/8c14cecc01b682510a4f57b837f6d374d9411836/src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift#L286), and to use that timestamp in the 4-hours check above.

@dsarkar please ask the developers if they agree with my ideas, and if they want (and have time) to try this.
Unfortunately I cannot offer a PR, my environment is currently broken ... 😱

**Comment by ndegendogo** [comment]
Wow, what an incident ... now I just got this error message myself ... 🤣

**Comment by ndegendogo** [comment]
So, answering all the questions that arise in such a case:
* cwa 2.5.1 / iOS 14.4.1 / iPhone 8
* As you see in the screenshot, I got the message today at 08:33.
* I got the message just after I had opened the app today for the first time (actually, I wanted to add an entry to my contact diary).
* It was definitely not my first launch with cwa 2.5; I had gone through the "new features" dialog only a few days ago.
* I always exit my apps just with the home button, I never swipe them out of memory.
* Looking at my exposure logs, I see that there was a successfull check at 06:35 today (less than 4 hours ago) - see screenshot (and that one had been triggered from background)
* That check at 06:35 was more than 2 hours ago, and I have WLAN; so I think that unprocessed hourly files were available.
* When I open cwa again now (09:37, still less than 4 hours since the previous check), I get the error message again.

I will wait for 4 hours now till I try again.

***Any more questions?***

![20210718_ENFlog](https://user-images.githubusercontent.com/6118267/126059837-7a6ab9d2-d172-4715-95f0-028b01351414.png)

**Comment by ndegendogo** [comment]
... and the only irregularity I see in my ENF log is that tonight the check at 02:34 was skipped.
Although this happens often at night.
Note: I have WLAN coverage, and don't activate any specific power saving mode.

[ExposureChecks-2021-07-18.json.txt](https://github.com/corona-warn-app/cwa-app-ios/files/6835840/ExposureChecks-2021-07-18.json.txt)

**Comment by ndegendogo** [comment]
Update: At 09:59 I started cwa again to activate the logging function.
**This time I got no error message.**

**Comment by Ein-Tim** [comment]
@ndegendogo 

Dis the start screen of the app show "Risiko-Überprüfung fehlgeschlagen"? Or was the card still green?

**Comment by ndegendogo** [comment]
@Ein-Tim no, it just showed the green test at 06:35

**Comment by ndegendogo** [comment]
Or, can it be an "overhang" error message from a previous (failing) check in background mode? 
And I saw it only when I opened the app?

*... just wild guesswork...*

**Comment by ndegendogo** [comment]
Update: I did not open the app again during the day. **My risk check is back to normal**, I got a check from background at 14:17 and then at 18:28.

**Comment by ndegendogo** [comment]
What will happen if the ENF returns with error from detectExposures?
=> risk check failed 
=> cwa will store no new timestamp 
=> next trigger for risk check will get no rate limit 
=> cwa will call ENF before waiting another 4 hours 
=> ENF will return error 13?

**Comment by ndegendogo** [comment]
@dsarkar @heinezen have the developers started to work on this proposal? 
Would they accept a PR?
@Ein-Tim and me volunteer to do it 😁

**Comment by Ein-Tim** [comment]
Hi @dsarkar or @heinezen 

Did you ask the developers about @ndegendogo's [proposal](https://github.com/corona-warn-app/cwa-app-ios/issues/2758#issuecomment-883654556)? Would they accept a PR trying to fix this?

**Comment by heinezen** [comment]
@ndegendogo @Ein-Tim 

I've asked for clarification on this issue a while ago, but sadly didn't get an update so far. I can ask again, but there's nothing new to report so far.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen Okay, thanks. So if I understand this correctly, nobody is working on this and @ndegendogo and I can provide a PR.

**Comment by heinezen** [comment]
@Ein-Tim @ndegendogo Yeah, I don't think the dev team has something aainst a PR on this topic.

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
... just to document the key points of our [discussion with the devs](https://github.com/corona-warn-app/cwa-app-ios/pull/3284#issuecomment-890104094) so far ...
* according to Apple, error returns don't count against the ENF rate limit
* the root cause of ENError 13 is not yet understood, it occurs rarely, usually heals itself, and cannot be reproduced
* the risk of changing (and possibly breaking!) the well-working risk procedure is considered higher than the damage of this Error 13
* the suggestion is to investigate this further and to implement a "soft rate limit" instead

**Comment by Ein-Tim** [comment]
Please update to iOS 14.7.1 and report if this fixed the Error 13.

**Comment by Ein-Tim** [comment]
@mtrinkau 

Do you still have this issue?

**Comment by mtrinkau** [comment]
No - thanks for asking. At some point the issue has gone away. No idea why, but it now works normal.
BestMtrinkau 



Von der neuen AOL-App für iOS gesendet


Am Samstag, Januar 8, 2022, 11:34 AM schrieb Tim ***@***.***>:




@mtrinkau

Do you still have this issue?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ein-Tim** [comment]
@dsarkar 

This can be closed, too. Enjoy Enjoy!

**Comment by dsarkar** [comment]
@mtrinkau Thanks for the feedback! Closing this issue now! CC @Ein-Tim 

Enjoy the weekend, best wishes, DS

---
Corona-Warn-App Open Source Team
