### ISSUE TITLE
Exposure Checks only show 100 entries (checks of the last 7 days)

### ISSUE THREAD

**Issue by TeRe20200** [corona-warn-app/cwa-app-ios#934]
Hi everyone, 
just by accident, I checked in my **Exposure-Checks** on the app and the last date logged is the **14th**. I checked with my friends and my parents too, _80% of them have only logged in the last 7 days_, _20% have 14 days listed_. We are taking about mostly Apple devices here (but also there are two Androids that are not showing last 14 days). 

What shall we do? How can we solve this issue?

We do have the latest App-Update (Version 1.1.1) and those having only logged the last 7 days either updated on iOS 13.6, some didn’t. 

I’d be really thankful for some input and help. 

---
Internal Tracking ID: EXPOSUREAPP-1935

**Comment by neonhaxred** [comment]
Hello there. I found this thread via google. I am experiencing the very same problem on iOS 13.6. With today my oldest entry is 17.07.2020 – yesterday it was 14.07.2020.

I exported the logs and read the JSON-File and there are exactly 100 entries as you predicted. With today the oldest entry in the JSON file is 2020-07-14. There are no records for the 15th, it goes on with the 16th. This behavior is strange insofar as the phone is always on, Bluetooth is always on, I was in range of at least two people with the app every single day and have never flushed the cache nor did anything else (not even activating flight mode or so).

**Comment by SebastianWolf-SAP** [comment]
OK, also here we have a confirmation by several people. In this case it's confirmed. We will address this to Apple and keep the ticket open until it's resolved.

@TeRe20200 That's correct! This list only shows the check _history_. As long as you have 14 checks in the last 24 hours everything is working correctly!

Everybody else: You can verify that everything works correctly by counting the number of checks within the last 24 hours. This number should match (or be 1 less) the number of active days. So if you had the app running already in the last 2 weeks or longer, you should always see 14 checks (or sometimes 13 depending on some boundary conditions) in the last 24 hours.

**Comment by SebastianWolf-SAP** [comment]
And completely forgot: Thank you very much for reporting this, @TeRe20200! That could explain some strange feedback which we have received over the last week and that we couldn't categorize or find our properly! :)

**Comment by neonhaxred** [comment]
I do count 26 counts only for today. Just want to provide this information. ![image](https://user-images.githubusercontent.com/68651856/88190815-0824fd00-cc3b-11ea-820d-6cc8c894c104.png)

**Comment by TeRe20200** [comment]
> And completely forgot: Thank you very much for reporting this, @TeRe20200! That could explain some strange feedback which we have received over the last week and that we couldn't categorize or find our properly! :)

You are very welcome. Thank you for your help and reply. I hope you can help @neonhaxred too, that seems
to be a different problem there.

**Comment by SebastianWolf-SAP** [comment]
@neonhaxred 26 for one day seems to be a little too much... But probably we address that in a separate thread. Maybe there was a second check of the last 2 weeks (2 x 13 days) and thanks to iOS 13.6 we don't have that problematic rate limiting anymore. Did you update/reinstall the app today?

**Comment by neonhaxred** [comment]
I did not restart the tracing nor did I flush the data. I always updated iOS to its latest version + the app. 

Thanks for your kind replies btw!

**Comment by Mihahn** [comment]
Can confirm the behaviour on iOS 13.6. For me it's July 25th until July 31st – exactly 7 days and 100 entries.

Am I right that – by limiting it to 100 entries – all exposure data before the 25th got lost and if I had a match before the 25th (as it should be 14 days of logging) I can't be notified? That said the right information is not in the cwa (14/14 days) but in Apple's Privacy -> Health -> Exposure logging?

**Comment by neonhaxred** [comment]
> Am I right that – by limiting it to 100 entries – all exposure data before the 25th got lost

That's what no one knows for sure. It seems like the app is still working finde due to the fact that it seems like you just need to ensure that there are 14 checks in the last 24 hours (a number that you easily do exceed). This is not yet confirmed though

**Comment by tkowark** [comment]
Please keep in mind, that we are talking about the exposure check **log**. Limiting this to 100 entries only means that you cannot see earlier **checks** of the log. As noted in the screen before (Covid-19-Begegnungsaufzeichnungen), the collected RPIs are stored for 14 days. So, when the app does its daily check, it checks against the entire 14 days of stored RPIs.

The 14/14 (or now: Dauerhaft Aktiv) days are also independent of that, they just denote for how long exposure logging has been active on your device without being shut off by manual deactivation, putting the phone into flight mode, etc.

**Comment by Mihahn** [comment]
> Please keep in mind, that we are talking about the exposure check **log**. Limiting this to 100 entries only means that you cannot see earlier **checks** of the log. As noted in the screen before (Covid-19-Begegnungsaufzeichnungen), the collected RPIs are stored for 14 days. So, when the app does its daily check, it checks against the entire 14 days of stored RPIs.

Thanks for clarifying!

**Comment by Tho-Mat** [comment]
@SebastianWolf-SAP 
Any news from Apple about the 100 entries limit and when it will be removed?
The issue is now 25day old.

**Comment by thomasaugsten** [comment]
We forward this to Apple and Google and they still discussing if they can increase the value because of data protection and privacy reasons. We have no direct influence on the OS settings￼￼

**Comment by Tho-Mat** [comment]
@thomasaugsten 
Thanks for your quick answer.
Maybe I'm to stupid, but i do not see any data protection and privacy reasons here.

If the 14 day limit comes into account all protocol entries, except the last 13/14, have to be removed, since all other contain contact checks for dates that are more than 14 days old.

**Comment by neonhaxred** [comment]
Apple did not understand the problem yet. I sent them a screenshot of the problem once again and they said they're investigating

**Comment by thomasaugsten** [comment]
The issue is here some other apps using per check only one or two files this means with 100 entries you can look back 100 days.

**Comment by daimpi** [comment]
Why don't they (Apple/Google) make sure that they delete all entries older than 14 days, but show the ones which are more recent than that no matter how many entries there are?

**Comment by Ein-Tim** [comment]
With iOS 13.7, this problem is solved because now you find "all files in one file"
See the Screenshots:

![image](https://user-images.githubusercontent.com/67682506/91912440-6bcb2d00-ecb3-11ea-80f9-edba8e3a62c6.jpeg)

![image](https://user-images.githubusercontent.com/67682506/91912446-6ec61d80-ecb3-11ea-8de0-f12dc5fb37bb.png)

**Comment by daimpi** [comment]
Nice 😊 

How does the exported .json file look like, do you maybe wana share yours? 🙂

**Comment by Ein-Tim** [comment]
@daimpi For sure:

[ExposureChecks-2020-09-02.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5161283/ExposureChecks-2020-09-02.zip)

**Comment by daimpi** [comment]
@GPclips 
I think this issue can be closed since this problem seems to have been resolved by the release of iOS 13.7 / 14.

**Comment by PhilippBerl** [comment]
I have the same problem: 
CWA 1.3.2., iOS 13.7. 

CWA showed me first time last Friday 03.10.2020 "1 Begegnung mit niedrigem Risiko", yesterday 05.10.2020 "2 Begegnungen mit niedrigem Risiko" 
I am living alone, spending 95% of my time alone in my flat. I had no personal contact in the last 14 days that would meet the conditions to be in any way risky. (In der Realität kein einziger Kontakt unter 2 Meter länger als 5 Minuten.)

Although CWA is reporting 2 contacts with low risk, the iOS protocol of the exposure logs of the last 14 day shows 0 matches. 

Is this a problem of iOS or of CWA? Which system is determining system? 
Background of the question: Is the report in CWA false positive or is the report in iOS false negative? 

Best wishes from Berlin
[ExposureChecks-2020-10-05 Kopie.pdf](https://github.com/corona-warn-app/cwa-app-ios/files/5326462/ExposureChecks-2020-10-05.Kopie.pdf)

**Comment by neonhaxred** [comment]
> I am living alone, spending 95% of my time alone in my flat. I had no personal contact in the last 14 days that would meet the conditions to be in any way risky. (In der Realität kein einziger Kontakt unter 2 Meter länger als 5 Minuten.)


Bluetooth can pass through walls. Living near to a street or living next door to someone who is Covid-19 positive can be detected as a contact by the system although you were alone all the time in reality.

**Comment by PhilippBerl** [comment]
@neonhaxred  Thank you, of course I have checked this possibility.Of course I have examined this possibility in detail. But none of my direct neighbors in our apartment building (all of them have CWA activated as well) have similar reports or are Covid positive. 

Above all: In this case, the iOS exposure log would have to record two matches within the last 14 days? But there is no such match.

**Comment by neonhaxred** [comment]
> Above all: In this case, the iOS exposure log would have to record two matches within the last 14 days? But there is no such match.

That's true! It might be this issue here: https://rp-online.de/panorama/coronavirus/corona-warn-app-fehler-in-ios-kann-zu-irrefuehrender-risikobewertung-fuehren_aid-53279797

**Comment by PhilippBerl** [comment]
The crucial question is still: is the report in CWA false positive (is the report of "2 Begegnungen mit niedrigem Risiko" wrong) or is the report in iOS false negative (is the report, that here haven't been any matches wrong)?

**Comment by neonhaxred** [comment]
It seems like nobody does know that. If you ask me I'd say that I rather trust the iOS protocol than the app itself.

**Comment by PhilippBerl** [comment]
I am not a programmer or software developer. But it seems logical to me that the decisive protocol is that of the iOS and the CWA evaluates the results of the protocol. 
My idea is that the iOS protocol lists the raw data that is modulated into a result in the app. My idea is, roughly speaking, that the iOS sends the information to the app. So if there are no matches in the exposure log, this rather indicates that there is a bug in the app? 


Is there someone here who developed the app or who is responsible for developing the app and who can answer this question? 
It's actually about a real risk assessment.

**Comment by PhilippBerl** [comment]
And thank you very much for the answers!

**Comment by Ein-Tim** [comment]
@PhilippBerl and @neonhaxred 
Please see #1106

The current assumption is that CWA is right, the ENF returns the correct numbers of Encounters to CWA but doesn't writes it in the Log. 

> I am living alone, spending 95% of my time alone in my flat. I had no personal contact in the last 14 days that would meet the conditions to be in any way risky. (In der Realität kein einziger Kontakt unter 2 Meter länger als 5 Minuten.)

@PhilippBerl regarding this part of your comment, please see #1234.

**Comment by Ein-Tim** [comment]
> @GPclips 
> 
> I think this issue can be closed since this problem seems to have been resolved by the release of iOS 13.7 / 14.

@GPclips could you close this Issue please? 🙂

**Comment by PhilippBerl** [comment]
To be honest, I do not quite understand why this issue was closed. 

Has the problem been solved? 

I don't know yet whether the two low-risk encounters with a covid-positive test person shown in the CWA actually took place, if so, when they took place (because there is no match in the exposure log) and whether it was the same person twice or two different ones. 

I mention again that I was alone at home 95% of the time and personally had no contacts in the close range of <2 meters, which lasted longer than 5 minutes in the last weeks  (the only one has been in the Staatsbibliothek zu Berlin to pick up books, in 5 minutes – exactly this was on 25.09. Except this situation I was only moving in my car, but without any personal contacts). 

It can also be ruled out that I have a source of infection in a neighboring apartment, because the direct neighbors do not get an encounter reported on their CWA. I am in email/whatsapp-contact with all of our neighbors here in our apartment building, and most of them have the CWA. 


I believe that my case can be helpful to solve the problem, because I had no personal contacts in the last weeks, except the one case described above on 09/25, at the same time no hits in the iOS exposure log. 
These are two remarkable features at the same time....

Is it possible that the Bluetooth signal in the courtyard 10 meters away would register a person tested positive for Covid and this would be reported as an encounter in the app? 

Questions about questions.

**Comment by Ein-Tim** [comment]
> I don't know yet whether the two low-risk encounters with a covid-positive test person shown in the CWA actually took place, if so, when they took place (because there is no match in the exposure log) and whether it was the same person twice or two different ones.

But this Issue is "Exposure Checks only show 100 entries (checks of the last 7 days)", and this has been solved with iOS 13.7 and above. The Issue you are expieriencing is tracked here: #1106 

And this: 
> I mention again that I was alone at home 95% of the time and personally had no contacts in the close range of <2 meters, which lasted longer than 5 minutes in the last weeks (the only one has been in the Staatsbibliothek zu Berlin to pick up books, in 5 minutes – exactly this was on 25.09. Except this situation I was only moving in my car, but without any personal contacts).

has been tracked here: #1234 

Now clearer why this Issue has been closed?

> and whether it was the same person twice or two different ones. 

I'm not quite sure about that, maybe @ndegendogo can answer your question.

Cheers 👍

**Comment by PhilippBerl** [comment]
Ok vielen Dank! Was sich auch nicht verstehe ist, warum wir hier alle auf Englisch miteinander kommunizieren, für eine App, die nur in Deutschland funktioniert. Aber offenbar soll alles etwas komplizierter sein als es unbedingt sein müsste ;-) , besonders, wenn es man besorgt ist and something is not working properly.

Many many Thanks for your kind answers. 
Nevertheless I still don't find my problem solved and hope to get more information. 

I have posted  the exposure log above. There are much more than just 100 entries reported and the protocol shows correctly the last 14 days. 

Could please somebody give me more information?  
I have now spent the last two days with this issue and have 10 neighbors in worry, asking me for explanation.

**Comment by Ein-Tim** [comment]
Wir schreiben hier auf Englisch um auch der Internationalen Community und vor allem Entwicklern aus anderen Ländern die Möglichkeit zu geben mitzuarbeiten. Wenn es dich nicht stört würde ich deine Fragen trotzdem kurz auf Deutsch beantworten 😀

> I have posted the exposure log above. There are much more than just 100 entries reported and the protocol shows correctly the last 14 days

Ja, ich hab mir deinen Log angesehen und richtig, dort sind deutlich mehr als 100 Einträge und das ist auch gut so. Vor iOS 13.7 gab es den Fehler das in diesem Log nicht genug Einträge angezeigt wurden, deswegen gab es diesen Issue. Da Apple das aber ja mit iOS 13.7 gelöst hat, wurde der Issue jetzt geschlossen.

Wenn du sonst noch Fragen hast würde ich dich bitten Sie in #1106 zu stellen, dort könntest du auch noch [deinen ersten Kommentar](https://github.com/corona-warn-app/cwa-app-ios/issues/934#issuecomment-703514760) posten, wenn du magst. Aber musst du nicht, denn wie gesagt, dieser Fehler wird mit iOS 14.2 behoben.

**Comment by PhilippBerl** [comment]
@Ein-Tim Danke sehr! 
Thanks a lot. 

I am quite sure that I am not alone with this problem and 100% sure, that there are many many people as I am, who are in worry, because they try to be as careful as they can to avoid any potential Corona-contact, but receiving the report in CWA that they had – accordingly to the app – a suspicious contact, or maybe more of them "Begegnung mit geringem Risiko"

And I am very very sure that more 80% of these people, insecure and frightened do not know what to do. I assume most of them even would not have enough patience, time and maybe energy and technical knowhow to find this site here

**Comment by PhilippBerl** [comment]
So, @Ein-Tim, do you think the two contacts with low risk ("Begegnungen mit geringem Risiko") are real int the meaning, that they have happened? 
Thank you very much, once again!

**Comment by Ein-Tim** [comment]
@PhilippBerl 
Yes, I'm very sure these contacts happend, and even if this was someody walking on the other side of the street or something like this, the App will show it to you.

> And I am very very sure that more than 80% of these people, insecure and frightened do not know what to do. I assume most of them even would not have enough patience, time and maybe energy and technical knowhow to find this site here

I (and also the devs here) know that these Low Risk Encounters are a little bit tricky to understand, but thats why with version 1.3.2 you should see some more details about your Low Risk Encounter in the App.

**Comment by PhilippBerl** [comment]
@Ein-Tim 
Again, thank you very, very, very much for your kind and helpful answers. 

I have just received the 24h-updated report from my CWA, still reporting the contacts with low risk. 

If the contacts really happened, my only explanation indeed would be, that I walked around the street or just sitting in the car in the traffic jam and somebody farer away in the meantime has been tested positive. But in this cases the contact would have been <5 minutes and the distance >8 meters (in normal distance, but the Bluetooth-signal isn't that precise, if the iPhone has been in my jacket or in my car or in my apartment etc.) I agree totally with you, that these cases would be the only ones to explain, why I have to suspicious contacts reported in my CWA. 
Once again: Is a short contact <2-5 minutes and farer than 8 meters away really already registered as contact? 
I have read that these cases are filtered out, so that they are not reported in any case. 

I have updated the CWA yesterday, but I still have no more information about these two matches. The situation in the App is the same as yesterday. 
![IMG_4147](https://user-images.githubusercontent.com/72381557/95098540-1a3d1480-072f-11eb-9bf3-21ba788bb3bb.PNG)

**Comment by Ein-Tim** [comment]
> Again, thank you very, very, very much for your kind and helpful answers.

No problem! @PhilippBerl 

> I have just received the 24h-updated report from my CWA, still reporting the contacts with low risk.

Means the contacts aren't already 14 days in the past, 14 days after the Encounter the App won't show them anymore.

> Once again: Is a short contact <2-5 minutes and farer than 8 meters away really already registered as contact?

Yes they are, see @kbobrowski's comment here: https://github.com/corona-warn-app/cwa-website/issues/307#issuecomment-679233521

>I have read that these cases are filtered out, so that they are not reported in any case.

Thats not true. Every Encounter will be shown to the User. 
(In earlier Versions of the FAQ there was the statement that some encounters are "verworfen", but since this isn't true, it was corrected.)

> I have updated the CWA yesterday to 10.3.2., before that I had the first version something like 10.01. or so, but I still have no more information about these two matches. The situation in the App is the same as yesterday.

Nice to hear that you updated, just a quick hint from me:
I don't know how you do it with other Apps but I would recommend to keep CWA always up to date 👍
Regarding no more Information:
If you click on the Green Card, this Screen should open: 
![image](https://user-images.githubusercontent.com/67682506/95100293-4063b400-0731-11eb-9ba6-65c000ca6d22.jpeg)

There you can find more Information about Low Risk Encounters. 

> I have also updated my iOS to 10.14.01. today without any changes regarding the exposure log, but this seems to be evident to me, unfortunately

Apple didn't change the Log with iOS 14.0.1, but they will solve the Issue #1106 with iOS 14.2

**Comment by PhilippBerl** [comment]
@Ein-Tim 
Thank you, great! 

> 
> > I have read that these cases are filtered out, so that they are not reported in any case.
> 
> Thats not true. Every Encounter will be shown to the User.
> (In earlier Versions of the FAQ there was the statement that some encounters are "verworfen", but since this isn't true, it was corrected.)

**This was one of the answers I was searching for.** 

It was this formulation, which is most irritating "is discarded". 
I would like to strongly recommend the developers or maintainers of the CWA to clarify this explicitly somewhere, because this explanatory text can be accessed unchanged and seems to be actual. 

> If you click on the Green Card, this Screen should open:
> Thanks also for this hint. I already know this page of the CWA, but it is of course much too general for a scientist like me and someone who wants to know the source of a danger exactly. 
> 
Thank you also very for that information. I already knew this Screen,  but it is of course **much too general** for a scientist like me and someone who wants to know the source of a risk exactly, although I respect the problem of Privacy Policy (Datenschutz). 

So once again a question of understanding. Assuming that the exposure log protocol in iOS would work without problems, these two matches would be displayed with date. That means: They would be completely anonymous, but at least I would know when the encounter was. 
And then I could better assess my personal risk. 
If, for example,CWA shows a contact with low risk, than I can see into the log and find the match. Let was say it was x-day. If I have been only at home that day, I would know that someone was maybe walking through the courtyard who later had been tested positive; or I would know "Aha, there was a parcel carrier who left a package at my door" or, I had fetched my books from the library etc. 
This is what I miss at the moment. 
Am right in assuming, that if everything would have worked properly with iOS , this would be a way to better limit the risk encounter and thus better assess the actual risk individually?
And that's where I still see the problem: As I said, in my case it is an extreme coincidence that the app shows these encounters and that they are not reported in the exposure log.

**Comment by daimpi** [comment]
> Assuming that the exposure log protocol in iOS would work without problems, these two matches would be displayed with date. That means: They would be completely anonymous, but at least I would know when the encounter was.
And then I could better assess my personal risk.
If, for example,CWA shows a contact with low risk, than I can see into the log and find the match. Let was say it was x-day. If I have been only at home that day, I would know that someone was maybe walking through the courtyard who later had been tested positive; or I would know "Aha, there was a parcel carrier who left a package at my door" or, I had fetched my books from the library etc.
This is what I miss at the moment.
Am right in assuming, that if everything would have worked properly with iOS , this would be a way to better limit the risk encounter and thus better assess the actual risk individually?

Unfortunately not. Even if EN log was working properly there is currently no direct way to find out when the green encounter happened (unless you have a rooted Android phone, in which case you can use [corona-warn-companion-android](https://github.com/mh-/corona-warn-companion-android) to get more info). There is only an indirect way to find out when the encounter was, by checking when the encounter disappears in CWA. I've written about this in some more detail [here](https://github.com/corona-warn-app/cwa-app-android/issues/1217#issuecomment-697631273) if you're interested.

I also wish there was more information shown for green encounters and we have an issue for this which you can upvote [here](https://github.com/corona-warn-app/cwa-wishlist/issues/178) 🙂.

**Comment by Ein-Tim** [comment]
![image](https://user-images.githubusercontent.com/67682506/95105814-fb8f4b80-0737-11eb-86c6-cee19b328989.png)

This du how is how it would look like if everything would be correct...

**Comment by PhilippBerl** [comment]
@Ein-Tim 
Exactly! And mine looks like this: 
![Bildschirmfoto 2020-10-05 um 18 50 47](https://user-images.githubusercontent.com/72381557/95108763-fd5b0e00-073b-11eb-9d37-1b5120a2f7e4.png)

Now, in the meantime have asked my neighbor to send me her protocol. Her CWA shows 1 "Begegnung mit geringem Risiko". 
Her protocol also shows no match in the last 14 days **BUT** 
her protocol shows several matches in 15.09. and 16.09. and INDEED she had been at a funeral with 20 persons, of which 15 (!) later tested positive. I don't want to know if her CWA signaled red, but she btw she had been tested negative and has been healthy ever since. 
But I try to understand: Are these matches logged, precisely because they were in fact very likely to be classified as risky encounters?

In any case, it proves that it makes sense to use the protocol to narrow down the date of the matches also in case of "Begegnungen mit geringen Risiko". Or is there an error in reasoning? At least it is the date on which the server sends the data to the iPhone, and in this way it is possible to narrow things down.

**Comment by PhilippBerl** [comment]
@daimpi 
`Unfortunately not. Even if EN log was working properly there is currently no direct way to find out when the green encounter happened (unless you have a rooted Android phone, in which case you can use corona-warn-companion-android to get more info). There is only an indirect way to find out when the encounter was, by checking when the encounter disappears in CWA.
 I've written about this in some more detail here if you're interested.`

But I don't understand that, please help me to understand it. If EN (EN is the acronym for the "protocol", I assume) shows 1 Match as @Ein-Tim has just shown it, than the match is related to a specific date. And that date gives at least an idea, when the contact happened.

**Comment by Ein-Tim** [comment]
@PhilippBerl 
Yeah, your log is showing no match because you are not on the iOS 14.2 Public Beta 2 as I am. 

>But I try to understand: Are these matches logged, precisely because they were in fact very likely to be classified as risky encounters?

I don't know when something is still loged and when not, but normally everything should be loged. 

>In any case, it proves that it makes sense to use the protocol to narrow down the date of the matches also in case of "Begegnungen mit geringen Risiko". Or is there an error in reasoning? At least it is the date on which the server sends the data to the iPhone, and in this way it is possible to narrow things down.

Yeah maybe the log can help you to narrow it down but to know when a Low Risk Encounter occured you just have to take a look in the App every day and when the Encounter isn't shown anymore, then you know your encounter happened 14 days ago. You understand? 😀

P.S.: EN is the abbreviation for Exposure Notification.

>than the match is related to a specific date

Yes, but the time shown in the Settings is only the Time when your App downloaded the keys from the Server, not the Time you met someone.

**Comment by PhilippBerl** [comment]
Great, @Ein-Tim 
After 24 hours I really start to understand how the CWA works. Amazing system. 
Although it is obviously the best compromise between Datenschutz and Infektionsschutz (sorry for writing this in German), there is really place to improve CWA by allowing either EN or CWA or both, to help the consumer and potential infected person to narrow down the date of the suspicious contact. This really would be a great help, in particular regarding the fact that unfortunately many people don't use the CWA.

**Comment by Ein-Tim** [comment]
Yes the date would be very helpful, this is requested (as @daimpi mentioned before) here: https://github.com/corona-warn-app/cwa-wishlist/issues/178

**Comment by PhilippBerl** [comment]
@Ein-Tim 
`Yeah, your log is showing no match because you are not on the iOS 14.2 Public Beta 2 as I am.`
Does this mean that if I would install iOS 14.2 Beta it would be possible to have access to the correct EN for the last 14 days - that means retroactively?

**Comment by Ein-Tim** [comment]
@PhilippBerl 
Puuh, not surr about that... 
I don't think so, because all the updates Apple ever made to the EN(F) weren't retroactively.

**Comment by daimpi** [comment]
@PhilippBerl 
> Does this mean that if I would install iOS 14.2 Beta it would be possible to have access to the correct EN for the last 14 days - that means retroactively?

Same as @Ein-Tim I'm not sure about this, but if the issue is fixed in iOS 14.2 Beta2 and you currently still see the encounter in CWA you could update to the beta and next time your CWA performs a sync/update, your log should show the matches. You can then put your log into [EN analyzer](https://felixlen.github.io/ena_log/) to see when the package with which you have a match was uploaded.



> > But I try to understand: Are these matches logged, precisely because they were in fact very likely to be classified as risky encounters?
> 
> I don't know when something is still loged and when not, but normally everything should be loged.

[This is correct](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-678768765). ENF is continuously recording all rolling proximity identifiers (RPIs) to later match them with keys (downloaded from the server) of users who tested positive. I've written in more detail how encounters translate to matches [here](https://github.com/corona-warn-app/cwa-app-ios/issues/1096#issuecomment-688235743) if you're interested.

Additionally: if you're interested to learn more details on how matches are phased out of the log you might want to check out [this thread](https://github.com/corona-warn-app/cwa-app-android/issues/1302).

On a more general note: in the context how CWA works I can recommend this [cute explainer](https://ncase.me/contact-tracing/) which imho describes the high level idea underlying CWA and other digital contact-tracing Apps very well 🙂.

**Comment by ndegendogo** [comment]
> Does this mean that if I would install iOS 14.2 Beta it would be possible to have access to the correct EN for the last 14 days - that means retroactively?

@PhilippBerl I don't expect this. As far as I understand, it is really only a log file of the checks. The result to cwa is independent.

I had a 'funny' experience at the time when they introduced this bug with iOS 13.7.
One day (still on iOS 13.6.1) I had one low-risk encounter. Both cwa and the EN exposure log showed it.
Next day I upgraded to iOS 13.7. That day cwa showed still/again the low-risk encounter, but EN log showed no match. 
But the old log entry of yesterday with the match was still there.

**Comment by ndegendogo** [comment]
> thats why with version 1.3.2 you should see some more data

@Ein-Tim 
[your comment](https://github.com/corona-warn-app/cwa-app-ios/issues/934#issuecomment-703689027) you mean cwa 1.3.2 or iOS 14.2 beta?
Because my understanding was that our request for more details is still on the wishlist?

**Comment by Ein-Tim** [comment]
@ndegendogo 
I mean CWA 1.3.2/1.3.1 because they updated the texts when you had a Low Risk Encounter, see my screenshot [above](https://github.com/corona-warn-app/cwa-app-ios/issues/934#issuecomment-703712632)

**Comment by ndegendogo** [comment]
@Ein-Tim thanks for pointing this out. I think this text is a lot better than the previous, because it explains what has happened.

**Comment by PhilippBerl** [comment]
@Ein-Tim @ndegendogo @daimpi @thomasaugsten @neonhaxred 

Once again I would like to thank you very much for your very helpful answers. I have learned a lot about the CWA and the way it works. 
Just to keep you informed: I have updated my iPhone (7 Plus) to 14.2 Beta2 now. As already thought the EN hasn't change. 

But the EN should be actualized within the next hour, when the CWA's data is updated in the usual 24-hour cycle. I am curious what will happen then.

**Comment by PhilippBerl** [comment]
@Ein-Tim @ndegendogo @daimpi @thomasaugsten @neonhaxred 


So, this is really incredibly interesting. 
At 17:34 the data of my CWA has been updated. Unchanged the CWA shows two low risk encounters.  Under iOS 14.2 the new NE shows - as it should - two matches. 
The two Hashs who have the match carry today's date.  
I have now tried to find these two Hashs again in the 14-day history of the logs. 
I have to mention briefly: I received the first message about a low risk match on 01.10. This hash, which is displayed today as a match, also goes back exactly to 01.10., i.e.: the hash can be found in the EN daily (of course according to the old list with 0 matches), 01.10., 02.10., 03.,10.
I received the second message about a low risk match on 04.10. The hash for this one is again on 05.10 and today. 

Now I have compared the NE of my neighbor (iOS 13.7) from yesterday with my one from today and checked if the hashs that are connected to a match at my place also appear at her place: They appear at her place, too, on the same days! 

Question: can we conclude from this that we have a positive-tested person here in our environment? How can the recurring hashs be interpreted differently? 

Then I have another news for you. Today I sent the RKI Information Center the suggestion quoted from my email below. The lady very kindly wrote back that she has already forwarded the suggestion. 

I wrote:
"[...]Sie können gerne diese Email mit meiner dringenden Empfehlung an die Entwicklungsabteilung weiterleiten, im Falle der Meldung niedrigschwelliger Risiko-Begegnungen (grüner Bereich) eine wenigstens schätzungsweise Rückverfolgung auf das Datum der Begegnung zuzulassen.
Dies würde die persönliche Risiko-Einschätzung erheblich erleichtern und sowohl eine trügerisch gefühlte Sicherheit als auch übertriebene Beunruhigung verhindern helfen. Der Zweck der Mitteilung niedrigschwelliger Risiko-Begegnung in de CWA ist ja trotz der Bewertung eines geringen Risikos, auf ein tatsächlich wenigstens theoretisch erhöhtes Infektionsrisiko hinzuweisen, so gering es auch gewesen sein mag.
Hier ist im Interesse des Infektionsschutzes Verbesserungsbedarf, der dennoch mit dem Datenschutz nicht kollidiert."
Answer: 
"[....] wir haben Ihre Hinweise bereits im Haus an die entsprechenden Stellen weitergeleitet."

Hopefully this will help to further improve the CWA, I would be happy if I could make a contribution. I expect a hard winter full of infections, in which the CWA can be a real help. The more infected people we unfortunately will have, and hopefully the more users of the CWA we will have, the more important it will be that the app will provide meaningful information also and maybe especially in low risk encounters. 

But now to my questions: Is it possible to trace or at least to narrow down possible sources via the hashs from the EN?  
In this case, where I have just been alone in my apartment - but the same hashs are shown over several days: does this indicate, that there is somebody here in range of my bluetooth signal who is tested positive and uses the CWA?
 

[ExposureChecks-2020-10-06.pdf](https://github.com/corona-warn-app/cwa-app-ios/files/5335260/ExposureChecks-2020-10-06.pdf)
[ExposureChecks-2020-10-05.Neighbor.pdf](https://github.com/corona-warn-app/cwa-app-ios/files/5335262/ExposureChecks-2020-10-05.Neighbor.pdf)

**Comment by PhilippBerl** [comment]
![Uploading Bildschirmfoto 2020-10-06 um 18.32.56.png…]()

**Comment by Ein-Tim** [comment]
@PhilippBerl 
>At 17:34 the data of my CWA has been updated. Unchanged the CWA shows two low risk encounters. Under iOS 14.2 the new EN shows - as it should - two matches. 

Perfect, thats how it should be. 👍

>Now I have compared the EN of my neighbor (iOS 13.7) from yesterday with my one from today and checked if the hashs that are connected to a match at my place also appear at her place: They appear at her place, too, on the same days!

Thats, too, how it should be.

>Question: can we conclude from this that we have a positive-tested person here in our environment? How can the recurring hashs be interpreted differently?

No you can't. The hashes are the same for everyone using CWA. The first hash is the newest hash (published yesterday or today), and the second is the one from yesterday or the day before yesterday. And all these hashes include the Keys from the positive tested persons who are using CWA (and some empty Keys, so that it isn't possible to know how many people submitted their positive test result via CWA). Did this answer your question, if not just ask 👍 

Regarding your E-Mail, the date (exactly the days since a) Low-Risk encounter happened should ihmo be showed, here is the Issue requesting this: https://github.com/corona-warn-app/cwa-wishlist/issues/178

>In this case, where I have just been alone in my apartment - but the same hashs are shown over several days: does this indicate, that there is somebody here in range of my bluetooth signal who is tested positive and uses the CWA?

Yes, it could be that somebody from your neighbours tested positiv but as said before, because of the high data privacy design by CWA and ENF it is not really possible to identify where your contact was. 

Stay safe and healthy!

**Comment by PhilippBerl** [comment]
@Ein-Tim 
> Did this answer your question, if not just ask 👍
To be very honest, I just start to understand but I am not quite sure. 
To regard it practically. I have now asked a second neighbor in our apartment building to share her EN. Her configuration: iOS 14.01, CWA 1.3.2. CWA says, she has no risk encounters. 
So I have three EN, mine, 1. Neighbor (as mentioned yesterday, she has 1 encounter), 2. Neighbor (0 encounter). 

Now I have compared my Match and the hash. Indeed the suspicious hash is also listed in both other EN: 

Mine:"Hash" : "99D35FBF030B71528DAA0BEAE55265B6A88821708B5C2A6FFABFE294F792C0EA",
"MatchCount" : 1,
"KeyCount" : 12850,
"AppBundleIdentifier" : "de.rki.coronawarnapp",
"Timestamp" : "2020-10-06 17:36:53 +0200"

Neighbor 1: 
"Hash" : "99D35FBF030B71528DAA0BEAE55265B6A88821708B5C2A6FFABFE294F792C0EA",
"MatchCount" : 0,
"KeyCount" : 12850,
"AppBundleIdentifier" : "de.rki.coronawarnapp",
"Timestamp" : "2020-10-05 18:11:07 +0200"

Neighbor 2: 
"Hash" :
"99D35FBF030B71528DAA0BEAE55265B6A88821708B5C2A6FFABFE294F792C0EA",
"MatchCount" : 0,
"KeyCount" : 12850,
"AppBundleIdentifier" : "de.rki.coronawarnapp",
"Timestamp" : "2020-10-06 01:10:02 +0200"

They are identical, but only in my case there was a match. 

Does this mean that the iPhones of both neighbors did not come within range of a device that sent this hash? 
Or does it mean that they also came into contact with this hash, and the hash simply does not directly represent an infected person?

**Comment by daimpi** [comment]
@PhilippBerl The hash can also be found [here](https://ctt.pfstr.de/json/filehashes.json): 
![grafik](https://user-images.githubusercontent.com/22129968/95242896-1d5c0180-0810-11eb-98fc-1b48838b5621.png)

This hash will be on everyone's phone because everyone will have downloaded the package with diagnosis keys (DKs) from Sept 30. This hash is only a identifying this daily package of DKs, it isn't influenced by matches or anything else…
